#This is my code to get nucleotide diversity estimates from GA and GAR cad86c Sanger data
#4/18/2019 MF
#alignment files generated by CLUSTAL Omega (1.2.4) multiple sequence alignment available 
#from EMBL-EBI

library(ape) #version 5.0
library(pegas)
library(FastaUtils)
source("https://bioconductor.org/biocLite.R")
biocLite("Biostrings")


#starting with primers 1b
CAD_GAR <- read.dna(file = "PATH/TO/FILE.aln", 
                      format = "clustal")

CAD_GA <- read.dna(file = "PATH/TO/FILE.aln", 
                      format = "clustal")

#Counting the number of segregating sites in these two datasets
seg_res <- seg.sites(CAD_GAR)
length(seg_res)

seg_sus <- seg.sites(CAD_GA)
length(seg_sus)

#getting theta
theta_res <- theta.s(CAD_GAR)
theta_res

theta_sus <- theta.s(CADsus_GA)
theta_sus

#getting pi
nuc_res <- nuc.div(CAD_GAR)
nuc_res

nuc_sus <- nuc.div(CAD_GA)
nuc_sus

real_diff <- nuc_sus-nuc_res


#resampling fasta files to generate new nuc div estimates

#First making resampled nuc_sus
GA_resamp_nucdiv <-numeric(0)
for (i in 1:1000){
fasta.sample(infile = "/PATH/TO/ALL.fasta", nseq = 48,
             replacement = FALSE, file.out = "out.GA")
GA_resamp <- read.FASTA(file = "~/out.GA")
GA_resamp_nucdiv<- c(GA_resamp_nucdiv, nuc.div(GA_resamp))
}

#Next making resampled nuc_res
GAR_resamp_nucdiv <-numeric(0)
for (i in 1:1000){
  fasta.sample(infile = "/PATH/TO/ALL.fasta", nseq = 44,
               replacement = FALSE, file.out = "out.GAR")
  GAR_resamp <- read.FASTA(file = "~/out.GAR")
  GAR_resamp_nucdiv<- c(GAR_resamp_nucdiv, nuc.div(GAR_resamp))
}

#getting the difference between pi estimates for resampled GA and GAR
resamp_diff_nucdiv <- GA_resamp_nucdiv - GAR_resamp_nucdiv

hist(resamp_diff_nucdiv, main = "CAD86c Distribution of NucDiv Diff")

sig <- sum(resamp_diff_nucdiv > real_diff)# shows the p-value for the permutation test.
